import javax.swing.*;
import java.awt.*;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rfrolow' at '2/19/15 1:22 PM' with Gradle 2.2.1
 *
 * @author rfrolow, @date 2/19/15 1:22 PM
 */
public class SwingDemo {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SimpleFrame frame = new SimpleFrame();
                frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                //frame.setUndecorated(true);
                //frame.setResizable(false);
                frame.setLocationByPlatform(true);
                frame.setTitle("My Title");
                Toolkit kit = Toolkit.getDefaultToolkit();
                Dimension screenSize = kit.getScreenSize();
                int screenWidth = screenSize.width;
                int screenHeight = screenSize.height;
                frame.setSize(screenWidth / 2, screenHeight / 2);
                frame.setVisible(true);
            }
        });
    }
}

class SimpleFrame extends JFrame {
    private static final int DEFAULT_WIDTH = 300;
    private static final int DEFAULT_HEIGHT = 300;

    public SimpleFrame() {
        setSize(DEFAULT_WIDTH, DEFAULT_HEIGHT);
    }
}