import javax.swing.*;
import java.awt.*;
import java.awt.font.FontRenderContext;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rfrolow' at '2/19/15 1:22 PM' with Gradle 2.2.1
 *
 * @author rfrolow, @date 2/19/15 1:22 PM
 */
public class SwingDemo {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SimpleFrame frame = new SimpleFrame();
                frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                //frame.setUndecorated(true);
                //frame.setResizable(false);
                frame.setLocationByPlatform(true);
                frame.setTitle("My Title");
                Toolkit kit = Toolkit.getDefaultToolkit();
                Dimension screenSize = kit.getScreenSize();
                int screenWidth = screenSize.width;
                int screenHeight = screenSize.height;
                frame.setSize(screenWidth / 2, screenHeight / 2);
                frame.setVisible(true);
            }
        });
    }
}

class SimpleFrame extends JFrame {
    private static final int DEFAULT_WIDTH = 300;
    private static final int DEFAULT_HEIGHT = 300;

    public SimpleFrame() {
        setSize(DEFAULT_WIDTH, DEFAULT_HEIGHT);
        add(new NotHelloWorldComponent());
        pack();
    }
}

class NotHelloWorldComponent extends JComponent {
    public static final int MESSAGE_X = 75;
    public static final int MESSAGE_Y = 100;
    public static final int DEFAULT_WIDTH = 300;
    public static final int DEFAULT_HEIGHT = 200;
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;

        Font f = new Font("SansSerif", Font.BOLD, 18);
        g2.setFont(f);

        String message = "My Component string";
        FontRenderContext context = g2.getFontRenderContext();
        Rectangle2D bounds = f.getStringBounds(message, context);

        double paddingHoriz = (getWidth() - bounds.getWidth()) / 2;
        double paddingVert = (getHeight() - bounds.getHeight()) / 2;
        double ascent = -bounds.getY();
        double baseY = paddingVert + ascent;

        g2.drawString(message, (int) paddingHoriz, (int)baseY);

        g2.setPaint(Color.LIGHT_GRAY);
        Line2D.Double line = new Line2D.Double(paddingHoriz, baseY, paddingHoriz + bounds.getWidth(), baseY);
        g2.draw(line);
        Rectangle2D rect = new Rectangle2D.Double(paddingHoriz, paddingVert, bounds.getWidth(), bounds.getHeight());
        g2.draw(rect);
    }

    public Dimension getPreferredSize() { return new Dimension(DEFAULT_WIDTH, DEFAULT_HEIGHT); }
}