import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'rfrolow' at '2/19/15 1:22 PM' with Gradle 2.2.1
 *
 * @author rfrolow, @date 2/19/15 1:22 PM
 */
public class SwingDemoTest {
    @Test public void testSomeLibraryMethod() {
        SwingDemo classUnderTest = new SwingDemo();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
